[project]
name = "gabriel"
version = "0.1.0"

[project.scripts]
gabriel = "gabriel.utils:main"

[tool.isort]
profile = "black"

[tool.black]
line-length = 100

[tool.pytest.ini_options]
addopts = "--cov=gabriel --cov-report=xml --cov-report=term"
testpaths = ["tests"]

[tool.coverage.run]
source = ["gabriel"]
branch = true

[tool.coverage.xml]
output = "coverage.xml"
