name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: Describe the bug and steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, dependencies.
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Anything else?
    validations:
      required: false
