name: Feature Request
description: Suggest an idea
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the proposed feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions?
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional context
    validations:
      required: false
