"""Core utilities for the Gabriel project."""

from __future__ import annotations

from .__about__ import (
    __author__,
    __keywords__,
    __license__,
    __summary__,
    __uri__,
    __version__,
)
from .analysis import (
    PhishingFinding,
    Recommendation,
    RiskTolerance,
    _registrable_domain_for,
    _split_registrable_domain,
    analyze_text_for_phishing,
    analyze_url,
    extract_urls,
    generate_recommendations,
    load_policy_document,
    validate_policy_document,
    validate_policy_file,
)
from .arithmetic import add, divide, floordiv, modulo, multiply, power, sqrt, subtract
from .common import (
    DEFAULT_SECRET_STORE,
    MAX_VECTOR_TTL,
    SECRET_ENV_PREFIX,
    KeyringSecretStore,
    ScratchSpace,
    SecretStore,
    SecureVectorStore,
    VectorRecord,
    _env_secret_key,
    read_secret_from_input,
    scratch_space,
)
from .ingestion import (
    CommitRecord,
    RepositoryCommits,
    collect_repository_commits,
    sanitize_prompt,
)
from .knowledge import KnowledgeStore, Note, SearchResult, load_notes_from_paths
from .notify import TokenPlaceClient, TokenPlaceCompletion, TokenPlaceError
from .secrets import delete_secret, get_secret, store_secret
from .selfhosted import (
    CheckResult,
    DockerDaemonConfig,
    NextcloudConfig,
    PhotoPrismConfig,
    Severity,
    SyncthingConfig,
    VaultWardenConfig,
    audit_docker_daemon,
    audit_nextcloud,
    audit_photoprism,
    audit_syncthing,
    audit_vaultwarden,
)
from .ui import (
    DEFAULT_HOST,
    DEFAULT_PORT,
    ViewerServer,
    serve_viewer,
    start_viewer_server,
)

SUPPORTED_PYTHON_VERSIONS = ("3.10", "3.11")

__all__ = [
    "__version__",
    "__summary__",
    "__uri__",
    "__author__",
    "__license__",
    "__keywords__",
    "add",
    "subtract",
    "multiply",
    "divide",
    "power",
    "modulo",
    "floordiv",
    "sqrt",
    "store_secret",
    "get_secret",
    "delete_secret",
    "SecretStore",
    "KeyringSecretStore",
    "ScratchSpace",
    "SecureVectorStore",
    "DEFAULT_SECRET_STORE",
    "SECRET_ENV_PREFIX",
    "MAX_VECTOR_TTL",
    "_env_secret_key",
    "read_secret_from_input",
    "scratch_space",
    "VectorRecord",
    "load_notes_from_paths",
    "KnowledgeStore",
    "Note",
    "SearchResult",
    "_registrable_domain_for",
    "_split_registrable_domain",
    "extract_urls",
    "analyze_url",
    "analyze_text_for_phishing",
    "PhishingFinding",
    "load_policy_document",
    "validate_policy_document",
    "validate_policy_file",
    "generate_recommendations",
    "Recommendation",
    "RiskTolerance",
    "DockerDaemonConfig",
    "VaultWardenConfig",
    "SyncthingConfig",
    "NextcloudConfig",
    "PhotoPrismConfig",
    "CheckResult",
    "Severity",
    "audit_docker_daemon",
    "audit_vaultwarden",
    "audit_syncthing",
    "audit_nextcloud",
    "audit_photoprism",
    "TokenPlaceClient",
    "TokenPlaceCompletion",
    "TokenPlaceError",
    "sanitize_prompt",
    "collect_repository_commits",
    "RepositoryCommits",
    "CommitRecord",
    "SUPPORTED_PYTHON_VERSIONS",
    "serve_viewer",
    "start_viewer_server",
    "ViewerServer",
    "DEFAULT_HOST",
    "DEFAULT_PORT",
]
