name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install commitlint dependencies
        run: npm ci
      - name: Determine base commit
        id: commit_range
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "base=${{ github.event.pull_request.base.sha }}" >> "$GITHUB_OUTPUT"
          else
            echo "base=${{ github.event.before }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Lint commit messages
        run: |
          set -euo pipefail
          BASE="${{ steps.commit_range.outputs.base }}"
          if [ -z "$BASE" ]; then
            BASE=$(git rev-list --max-parents=0 HEAD | tail -n 1)
          fi
          npx commitlint --from="$BASE" --to="$GITHUB_SHA"
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt
          uv pip install --system bandit flake8 ruff pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run Ruff
        run: ruff check --output-format=github .
      - name: Run Flake8
        run: flake8 .
      - name: Run Bandit
        run: bandit -c pyproject.toml -r gabriel scripts
