name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: |
          uv pip install --system flake8 bandit
      - name: Run Flake8
        run: flake8 .
      - name: Run Bandit
        run: bandit -r .
