name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt
          uv pip install --system bandit flake8 ruff pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run Ruff
        run: ruff check --output-format=github .
      - name: Run Flake8
        run: flake8 .
      - name: Run Bandit
        run: bandit -c pyproject.toml -r gabriel scripts
