name: Coverage
on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install spellcheck dictionaries
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Cache uv dependencies
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
          else
            uv pip install --system -r requirements.txt
          fi
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Node dependencies
        run: npm ci
      - name: Run viewer tests
        run: npm run test:ci
      - name: Run tests with coverage
        run: |
          pytest --cov=gabriel --cov-report=term-missing --cov-report=xml
          coverage-badge -o coverage.svg -f
      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Commit coverage badge
        if: >-
          runner.os == 'Linux' &&
          matrix.python-version == '3.10' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: coverage.svg
          message: "chore: update coverage badge [skip ci]"
