name: Coverage
on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install spellcheck dictionaries
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-${{ matrix.python-version }}-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt
      - name: Run tests with coverage
        run: |
          pytest --cov=gabriel --cov-report=term-missing --cov-report=xml
          coverage-badge -o coverage.svg -f
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Commit coverage badge
        if: >-
          matrix.python-version == '3.10' &&
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: coverage.svg
          message: "chore: update coverage badge [skip ci]"
