name: Coverage
on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt
      - name: Run tests with coverage
        run: |
          pytest --cov=gabriel --cov-report=term-missing --cov-report=xml
          coverage-badge -o coverage.svg -f
      - name: Commit coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: coverage.svg
          message: "chore: update coverage badge [skip ci]"
