name: Build Docker Image
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image for scan
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:scan
      - name: Install Trivy
        uses: aquasecurity/setup-trivy-action@v0.12.0
      - name: Scan built image with Trivy
        env:
          TRIVY_CACHE_DIR: ${{ runner.temp }}/trivy-cache
          IMAGE_DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          python3 -m gabriel.security.container_scanning "ghcr.io/${{ github.repository }}@${IMAGE_DIGEST}" \
            --extra-arg --cache-dir \
            --extra-arg "${{ runner.temp }}/trivy-cache"
      - name: Promote scanned image tags
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
            ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}
