name: Build Docker Image
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image for vulnerability scan (${{ matrix.platform }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: ${{ matrix.platform }}
          load: true
          tags: ghcr.io/${{ github.repository }}:scan-${{ matrix.platform }}
      - name: Install Trivy
        uses: aquasecurity/setup-trivy-action@v0.12.0
      - name: Scan image with Trivy (${{ matrix.platform }})
        env:
          TRIVY_CACHE_DIR: ${{ runner.temp }}/trivy-cache
        run: |
          python3 -m gabriel.security.container_scanning "ghcr.io/${{ github.repository }}:scan-${{ matrix.platform }}" \
            --extra-arg --cache-dir \
            --extra-arg "${{ runner.temp }}/trivy-cache"
      - name: Remove local scan image (${{ matrix.platform }})
        if: always()
        run: docker image rm ghcr.io/${{ github.repository }}:scan-${{ matrix.platform }} || true

  build:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
