name: Spell Check
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: markdown
            pattern: '**/*.md'
          - name: python
            pattern: '**/*.py'
    steps:
      - uses: actions/checkout@v3
      - uses: crate-ci/typos@v1
        with:
          files: ${{ matrix.pattern }}
          config: .typos.toml
